### ISSUE TITLE
Fast travel to HQ explode vehicules when multiples at the same time

### ISSUE THREAD

**Issue by zalexki** [A3Antistasi/A3-Antistasi#149]
*Version:* 1.2.5

*Mods:* CBA, TFAR, ACE(no-medical), RHSs

*Environment*: MP dedi.

*have you edited the missionfile?*: No

***Issue:***

Since we have a lot more people now it often happens that people RTB with fast travel and then loose their vehicules because it spawning on top of each other.

**Comment by Toakan** [comment]
Perform a check to see if any other vehicles are present around the Base flag, if there are, reject the Fast Travel with a message?

@Barbolani77

**Comment by Toakan** [comment]
If the check is in place, how are you able to fast travel to the Base flag in a vehicle when one is already present....

```if (((side _x == muyMalos) or (side _x == malos)) and (_x distance (getMarkerPos _base) < 300) and (not(captive _x))) exitWith {_chequeo = true};```

https://github.com/A3Antistasi/A3-Antistasi/blob/master/A3-Antistasi/fastTravelRadio.sqf

That's the line of code you're on about, and it doesn't contain a vehicle check.

**Comment by Barbolani77** [comment]
That snippet is for another purposes. Please keep in mind  this is  meant to be commmented by people  with some knowledge you clearly lack.

**Comment by Toakan** [comment]
Rather than being an ass, which section of the code explicitly checks for / prevents vehicles from fast travelling to the base if there is a vehicle present.

**Comment by Barbolani77** [comment]
Still with lacks of knowledge, making references to unrelated bugs, misunderstanding BIS commands, and now insulting. Prior to more sqf knowledge you have some social skills to improve.

**Comment by zalexki** [comment]
this bug is present and need to be fixed, let's hope someone make a PR as your pride cant handle someone trying to help verbally ...

**Comment by zalexki** [comment]
why closing when we can let it opened so someone can bring an idea and fix it ? 
like set some pre defined spot with and check with that like helipad thing or smaller if possible

**Comment by Barbolani77** [comment]
If you cannot understand the difference between real help and what Toakan makes, I will patently explain you:

First: He suggest to make a proximity check, which is like "have you tried to shutdown your PC?". That CAN be received as an offense. But patiently I reply "this is obviously done".

Second: He comes back saying "no you dont", pointing to the wrong line of code. That also CAN be received as an offense. My reply is: if you wanna help you need to know how this works. Of course this guy showed little knowledge and proofed he hasn't even readed the whole script. 

Third: calls me "an ass" and later, even pointing with the right line of code (this time he read the whole script) but he shows he still does not understand the command, what has been done prior to the command use, and point to the building boundingbox bug which is totally unrelated. That also CAN be received as an offense.

From now: I think there have been several times people has really helped here and their help has been very welcome, so saying "I cannot handle someone trying to help" (you edited it, before you were saying something like "it is because my pride") it is a fucking lie and obviously an offense.

There are other approaches to solve this, but I will put my hands on it as soon as my anger passess by.

**Comment by zalexki** [comment]
1. so why closing ? if this will be fixed then why not let other people brainstorm on this ?
2. you're intolerance is unbelievable.
3. your pride or anything else even in vacation you spit on people at sight with that `lol` and then make assumptions on a guy and heat the topic all by yourself in stead of a simple, `yes it is done`, `no it's not that i'll do it later`. look you even get angry while we are calmly trying to find a solution, learn the difference between steam and github, while here we try to find a solution. 
4. gosh you both lack the most basics of social skills ever, like `would` and `should` ? never heard of them ? omg !

**Comment by Barbolani77** [comment]
I may have little tolerance with randoms which make dumb assumptions and insult me, yes.

I may also lack of social skills because I am not native english or maybe because I think once I get insulted with "be an ass" or "not being able to handle someone trying to help" and then my reply sound rude. Or maybe that rudeness is a natural consequence.

I think a big difference with steam is this is not the place to post your first mind fart without documenting, checking etc. "Trying to search a solution" for me it's something very different. I don't make any assumption, this guy hasn't even readed the code at some point, in another point simply doesen't understands it. There are definetly better ways to make a proposal.

I've been developing this for long time and during it I have received very useful help from lots of people with no issues at all. Which is the opposite of what you said.

If you cannot stand my lack of social skills or think I shouldnt send to fuck off the first idiot that comes here to insult me, you know what to do.

If you at last understand why I don't tolerate this and your comments then you are welcome to help, or even post the code with the solution if you want.

**Comment by Barbolani77** [comment]
No. Because having vehicles present doesent mean there is no room for another one. Most of the times you may have a parked vehicle which wouldnt allow to FT.

Also, another FT may be inbound And the check would return empty with the same problem a second after.

Anyway I Will disable FT for players in MP because of Gameplay reasons.

**Comment by Toakan** [comment]
@zalexki Which vehicles are you seeing this issue with.

From experience, Its when players have FT' the HEMMT which causes the issues. Yet to see it with Quad-bikes / Offroads.

Maybe exclude larger vehicles rather than just disable it altogether?

**Comment by zalexki** [comment]
`you know what to do` well didnt have a choice haha you removed from the team you cranky old dude.

Oh wow you've been coding since a few years how impressive... (i'm starting my 12th ;) ) BTW this doesnt give you the right for being an asshole ;) you heat the topic by yourself and then blame others to respond to your, not done by mistakes, attacks ? you said it yourself ... years that you've been developping this and communicating in english dont try to hide your asshole responses behind this shitty language excuse.
( Also you can ask for people to properly understand your code when this one is properly readable and not in a spanglish weird thing with a non standard indentation ;) )

Oh it doesnt work on mp, let's remove it :joy: B. solution to MP problems except the one that nobody wants and kill the server every 30min haha you make me laugh sometimes.

You could just implement the same basic lock system present in the some points or cash counting in the code. If someone is FTing or 5s after. block every one else. 
There is also the helipad solution which has his own detection thing.

**Comment by Barbolani77** [comment]
Ok, ok, sorry @zalexki but I have to block you. 

And now sticking to the topic: any kind of vehicle may cause the issue, even a roadcone.

I insist the FT removal in MP it's because of gameplay issues.

One of the reasons of this bug is purely a bad parametrisation of the commands, which will be solved in the next patch, and that will help, but only help.

If instead of replying in that mood you document, understand the commands and the code and then make any kind of proposal, you would have noticed it.
