### ISSUE TITLE
Roadblocks bots

### ISSUE THREAD

**Issue by AlexTriada** [A3Antistasi/A3-Antistasi#172]
Version: <=1.3.5.2
Mods: CBA, TFAR, all RHS
Environment: MP dedi.
.rpt attatched? No
have you edited the missionfile?: No

At roadblocks bots are like idols, on the sides do not look, do not move, as if they are asleep until you start to shoot at them or drive up from the side in which they are ALL! looking

**Comment by Barbolani77** [comment]
That's because of UPSMon script, which does not make the AI patrol on very small areas. The areas in roablocks are defined very small because if not, AI would be patrolling very far from the RB position.

About the AI facing the same direction, that is an Arma thing. As long as the AI is on "SAFE" behaviour, they won't check for the perimeter and face the same direction than the squad leader uses.

I can do nothing

**Comment by AlexTriada** [comment]
You did such a good fucking mission, and now you're saying there's nothing you can do?  I don't believe you!))

**Comment by Barbolani77** [comment]
Well. "Something" can be done, but It would degrade a bit mission performance. In roadmap is to replace Upsmon, but until then, It Will keep this way
