### ISSUE TITLE
[bug] Towing very often not Working

### ISSUE THREAD

**Issue by gallexme** [A3Antistasi/A3-Antistasi#66]
*Version:* Newest https://github.com/A3Antistasi/A3-Antistasi/commit/871949b1352d0ca6bdfb1e0b0c4419ede1e48313
*Mods:* CBA, FFAA

*Environment*: MP dedi.

*.rpt attatched?* YES [log.rpt](https://github.com/A3Antistasi/A3-Antistasi/files/2010172/Arma3_x64_2018-05-16_17-25-28.-.Kopie.txt)

*have you edited the missionfile?*: No

***Issue: Towing not working***

Only after joining the server its working, later on it doesnt, dont know yet when exactly it stops working

**Comment by Barbolani77** [comment]
I will check, thanks!

**Comment by Barbolani77** [comment]
Hey! Two things.

You dont need XLA anymore in Antistasi.

What mod is Immerse?

**Comment by gallexme** [comment]
just visuals
http://www.armaholic.com/page.php?id=27847

**Comment by AlexTriada** [comment]
всё уже давно работает, закрывай

**Comment by deimerl** [comment]
No, this issue is still present. After you're downed then revived, towing does not show up on vehicles.

**Comment by Barbolani77** [comment]
Oh dear there you go, that gave me the tip.

Advanced Towing has a big design failure. Mousewheel actions are added to the player instead of the vehicles, which means, OMG , when you use the command to remove the actions, you remove them too.

Maybe I will build a fix, but it's definetly a bad design as those actions should be added to the vehicles, not the players.

**Comment by AlexTriada** [comment]
its only in vanilla

**Comment by Barbolani77** [comment]
which will be evaluated every frame... no. I repeat, Towing has a BIG design failure. Anyway I solved it by adding the actions again. This is solved a few patches ago.
