### ISSUE TITLE
[issue] Petros death code bulletproof

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/A3-Antistasi#71]
*Version:* 1.0.2A

*Mods:* CBA, TFAR, ACE(no-medical), RHS

*Environment*:MP dedi.

*.rpt attatched?* No

*have you edited the missionfile?*: No

***Issue:***
Petros death and move HQ could have some leaks considering it's the second time i hear on official server that, about this circumstance, HQ is builded in [0,0,0]

**Comment by Barbolani77** [comment]
Petros code protects him in all aspects I can imagine, no player can kill him, and, in case he dies because of AI or PvP players, the script waits for a player commander and asks for a new HQ placement.

So we will have to conduct several cheatbox textx everytime we find this. For example:

alive petros
position petros
isNull petros
isNil "petros"
getMarkerPos "respawn_guerrila"

**Comment by zalexki** [comment]
petros died due to ennemy mortar on official and it worked correctly asking me to replace HQ.
I think we can close this one.
